### ISSUE TITLE
2nd fan

### ISSUE THREAD

**Issue by drdilyor** [wotikama/nvidiafan#1]
Dude tysm you saved my life!!

But this will only set the first fan (`fan-0`). To set the second fan i modified the script like this (note the new parameter to nvidia-settings, with `fan-1`):

```bash
setfan() {
  xhost si:localuser:root
  echo $password | sudo -S /usr/bin/nvidia-settings -a "*:1[gpu:0]/GPUFanControlState=1" -a "*:1[fan-0]/GPUTargetFanSpeed=$1" -a "*:1[fan-1]/GPUTargetFanSpeed=$1"
  xhost -si:localuser:root
}

for(( ; ; ))
do
X=$(nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader)
if ((0<=X && X<=35))
then
  setfan 35
elif ((36<=X && X<=50))
then
  setfan 45
.......

```

I'm leaving this here in case anyone needs, or you can add this to your script as well.

**Comment by wotikama** [comment]
I'm grateful it was helpful. Thanks to you I realized just 1 fan was working for me too LOL.
