### ISSUE TITLE
shebang line mismatch

### ISSUE THREAD

**Issue by ghost** [wotikama/nvidiafan#3]
Why the `#!/bin/env bash` is for? it is unable to start up with autostart script with KDE Plasma, is that a Hyprland requirement?
Using EndeavourOS (Arch btw) too ;D

So I had to modify the first line to `#!/bin/bash` instead for it to actually launch via the KDE's autostart.

**Comment by wotikama** [comment]
Running a command through /usr/bin/env has the benefit of looking for whatever the default version of the program is in your current environment.

This way, you don't have to look for it in a specific place on the system, as those paths may be in different locations on different systems. As long as it's in your path, it will find it.

**Comment by ghost** [comment]
It was in my path, and still it did not find it and on top of that I was constantly locked out of my user account while the script ran and afterwards for the 10minute lockout (checked with `faillock`), due to invalid password attempts. Sorry for the feedback, I was trying to help, that maybe this nopasswd + env approach is not optimal. Falling back to tuxclocker.

**Comment by wotikama** [comment]
Probably you didnt set NOPASSWD correctly, i dont have an nvidia gpu anymore. Cant test, BUT when I did, it worked. try doing sudo /usr/bin/nvidia-settings ,if it asks for password then you didnt set it up correctly

**Comment by ghost** [comment]
> Probably you didnt set NOPASSWD correctly, i dont have an nvidia gpu anymore. Cant test, BUT when I did, it worked. try doing sudo /usr/bin/nvidia-settings ,if it asks for password then you didnt set it up correctly

Already did, and actually copypasted the commands from your readme file and rewrote `user` to my actual username ofcourse, triple checked it all was set, and /usr/bin/nvidia-settings was working when I called it manually but not when the script was ticking. Weird. Never mind then.
