### ISSUE TITLE
RROR: Error resolving target specification 'fan-0' (No targets match target specified in assignment '*:1[fan-0]/GPUTargetFanSpeed=55'.

### ISSUE THREAD

**Issue by kusowl** [wotikama/nvidiafan#4]
Script output
localuser:root being added to access control list

  Attribute 'GPUFanControlState' ([gpu:0]) assigned value 1.

ERROR: Error resolving target specification 'fan-0' (No targets match target specification),
       specified in assignment '*:1[fan-0]/GPUTargetFanSpeed=55'.

localuser:root being removed from access control list

i don't know why this is happening

**Comment by wotikama** [comment]
it may be because your graphics card isnt compatible with nvidia-settings fan control. You could open nvidia-setting when on X and see if fan control works.  Or it could be that your gpu is named gpu:1, fan:1 ,etc... Cant pinpoint the issue. You should also check how it is named

**Comment by scraprats** [comment]
This is because the card has only one fan. Confirmed on single fan GTX 950.

**Comment by wotikama** [comment]
Closing then. As said the script is a general one, manual modifications may be needed.
